### PR TITLE
EDACS: Test Call improvements

### PR DESCRIPTION
**Pull request by ilyacodes**
Mostly minor and cosmetic changes for visual (logging and ncurses) consistency across the board.

Fix an incorrect indexer `i` vs `j` in the ncurses matrix.

### CODE REVIEW

**Comment by lwvmobile** [comment]
```
[ 46%] Building C object CMakeFiles/dsd-fme.dir/src/edacs-fme.c.o
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c: In function ‘is_agency_call_group’:
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c:74:17: error: ‘state’ undeclared (first use in this function); did you mean ‘stat’?
   74 |   int fs_mask = state->edacs_s_mask | (state->edacs_f_mask << state->edacs_f_shift);
      |                 ^~~~~
      |                 stat
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c:74:17: note: each undeclared identifier is reported only once for each function it appears in
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c:75:30: error: expected ‘;’ before ‘}’ token
   75 |   return (afs & fs_mask) == 0
      |                              ^
      |                              ;
   76 | }
      | ~                             
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c: In function ‘is_fleet_call_group’:
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c:80:17: error: ‘state’ undeclared (first use in this function); did you mean ‘stat’?
   80 |   return (afs & state->edacs_s_mask) == 0
      |                 ^~~~~
      |                 stat
/SSD_STORAGE/2024_DEV/ilya/dsd-fme/src/edacs-fme.c:80:42: error: expected ‘;’ before ‘}’ token
   80 |   return (afs & state->edacs_s_mask) == 0
      |                                          ^
      |                                          ;
   81 | }
      | ~                                         
make[2]: *** [CMakeFiles/dsd-fme.dir/build.make:678: CMakeFiles/dsd-fme.dir/src/edacs-fme.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/dsd-fme.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by ilyacodes** [comment]
Just as a note, I don't have a great way to test the new AFS call type logging, no standard systems close enough to monitor and I don't really want to do this implementation for EA too. I don't know how often STM uses agency/fleet calls, but we can let it run for a while and see what turns up.

EDIT: and re compiler errors, yeah, that's what I get for pushing on my Windows dev laptop to pull on my build/test laptop while you happen to be looking, haha

**Comment by lwvmobile** [comment]
I'll try to test the A and F calls on STM, and see if there are any, that is, assuming that the AFS bit values are correct/known for that system at any rate. I honestly wouldn't bother doing it for EA either, sounds like too much of a hassle when you have to make assumptions as to how it is set up to begin with.

**Comment by lwvmobile** [comment]
Excuse me, sir, this is Florida, we don't do 'Math' around here! We aren't that sophisticated.

**Comment by ilyacodes** [comment]
I went ahead and tested the A/F flag changes by hard-coding in TG 288 (`0b001_0010_0000`) and then running with various `-fhXYZ` values and seeing which ones hit. The expected behaviour was that `XYZ` with `X >= 6` would flag as an agency call, and `XYZ` with `X < 6 && Z <= 5` would trigger as a fleet call, and it seemed to work.

**Comment by lwvmobile** [comment]
Yeah, that's probably the best way to do it is just to hard code some variables in there and make sure its behaving as expected. Currently, the ISP for the remote is slow and getting about a 1 mbps download on average, with upload much worse, so can't even barely control the desktop over there right now, let alone monitor anything on it.

**Comment by ilyacodes** [comment]
So I've been thinking about it, and the more I think, the more convinced I am that we should always **display** TGIDs as both decimal and `AA-FFS` (4:4:3) in the terminal, regardless of the user's input. The reasoning is as follows:
1. 4:4:3 AFS is a "standard" format among scanner types
2. It is known (among the relevant community) to read `XX-XXX` as `AA-FFS`
3. Displaying any other AFS pattern as `XX-XXX` leads to ambiguity as the number of digits will not match

Now, we could display TGs as `X:X:X` when a custom pattern is specified - and I have prepared a commit that does so - which resolves points 2 and 3. However, it does not address point 1, and results in either variable-length strings which mess up careful terminal formatting, or a painful amount of logic to avoid those.

I'm curious for your thoughts, but my proposal would be to **either**
- axe custom AFS patterns entirely, **or**
- always display as 4:4:3, but use custom patterns to detect agency and fleet calls

**Comment by lwvmobile** [comment]
I'd recommend taking a break for a couple days and enjoying the weekend. Think it over some but don't try to overdo it all at once. I feel like we are both probably overdoing it here right now, worried about little details that the end user may not even realize (assuming there are many of those on EDACS still anyways). When in doubt, KISS.

**Comment by lwvmobile** [comment]
Another thing, maybe you can clarify, because every time I read this I get a bit confused, but by default, aren't we already displaying the TG for EDACS standard as AA-FFS which is set to 4:4:3 by default without user intervention?

So, assume we have user input with custom AFS bit values, couldn't we simply have a variable such as `state->custom_afs` which when set by the input of -fh343 or similar, if flipped on, and if its tripped, we can use that to display a A:F:S value in the terminal instead of the AA-FFS variant?

```
if (state->custom_afs)
{
  //Display as A:F:S
}
else
{
 //Display as AA-FFS (what we are currently doing)
}
```

Maybe I also misunderstood earlier, but to detect Agency and Fleet Calls, can't we just make and/or use the agency and fleet bits and make a custom mask and do a `(group & a_mask) == 0` or `(group & f_mask) == 0` to determine when its an agency or fleet call, respectively?

**Comment by ilyacodes** [comment]
It's a bit spaghetti in some cases because now we have to check the exact length of the string from before, and use that to format the length of the non-group calls so that everything lines up in `ncurses`, but... it's not quite as bad as what I originally was trying.

I think once you look at 0568475 you'll see what I mean - it's far from killer, but it's a bit annoying to format it consistently regardless of the A:F:S split, without just making each section 3 digits.

I went ahead and tested it reasonably thoroughly against the Bexar data in particular, and it looks to work right.

**Comment by lwvmobile** [comment]
Anyways, you got any other updates or anything to add to this pull request, or can we go ahead and merge it? As far as I can tell, everything seems to be working good so far, haven't noticed any glaring issues, not to mention, we are veering far out of the scope of what the pull request was meant to cover at this point with all the AFS stuff, Dynamic Regrouping, and so on.

**Comment by ilyacodes** [comment]
Yep, perfectly good to merge - I wish there were a way to "stack" PRs on top of each other, that would make it much easier to track changes that are dependent on each other.

**Pull request merged**
