### PR TITLE
Sending Audio to a Icecast 2 Server via FFmpeg (Windows)

### PR DESCRIPTION
**Pull request by francisuk1989**
For them who wont to send audio to a icecast 2 server via WIndows.

### CODE REVIEW

**Comment by lwvmobile** [comment]
Have you got the heading on the correct line? Its on the second line and not the line above it? Wasn't sure how you wanted that formatted, you might consider using a ## instead of a single # for a subheader 2 or 3 (or whatever its called)

**Comment by francisuk1989** [comment]
> Have you got the heading on the correct line? Its on the second line and not the line above it? Wasn't sure how you wanted that formatted, you might consider using a ## instead of a single # for a subheader 2 or 3 (or whatever its called)

To be honest, Since this is your project, Ill let you take care of that 😃

**Comment by lwvmobile** [comment]
Okay doke, got it formatted a little clearer while leaving the content alone. I'll go ahead and merge now.

**Comment by lwvmobile** [comment]
> @lwvmobile on that note, i dont see any settings in the control panel on WIndows 10 to take the audio from pulse, Any ideas for a solution on pulse for WIndows?

I honestly don't. Windows isn't my forte, so I have no idea, other than that the pulse audio server application shows up as its own thing in the volume mixer, but its not an audio device, it's just software that interfaces to hardware and acts as a 'server' for 'clients' to connect to for audio sources and audio sinks. Even in Linux, Pulse Audio is slowly being phased out for Pipewire, but Pipewire maintains a backwards compatibility layer to anything calling pulse audio so its mostly seamles in that regard, unlike the transition from OSS to Pulse Audio, which in itself requires a wrapper 'padsp' to run properly, but has been noted to be broken in newer Ubuntu builds, but still seems to work in my Arch based desktop somehow when I use it for testing.

If I were more inclined, I would probably at some point attempt to make a version of DSD-FME that could be compiled and run natively on Windows without the Cygwin layer, but I have no idea about Windows Sound Architecture, or how easy or hard it would be to implement a native sound system for it. Other than that, I think a few odds and ends (mostly Winsock instead of socket and natively compiling rtl_fm, and maybe ncurses/pdcurses and posix pipes) would be the major hurdles to get a native Windows build.

**Comment by francisuk1989** [comment]
Notes for Linux users streaming to Icecast 2 with ffmpeg

1st - list pulse sources

`pactl list short sources`

then 0 beening my speakers.

ffmpeg -f pulse -i **0** -c:a libmp3lame -ab 64k -f mp3 icecast://source:mypassword@XX.XX.XX:8000/DSDFME

**Comment by lwvmobile** [comment]
Okay, I'll add that to the example on the next batch of commits.

**Pull request merged**
