### PR TITLE
EDACS: add EA messages / start mass Standard refactor

### PR DESCRIPTION
**Pull request by ilyacodes**
**EDACS Standard**

Begin mass refactor to actually use the standard, or the closest we have to a standard.

**EDACS EA**

Add two new CC messages:
- status/message
- channel assignment (unknown; data-related)

Refactor log entry format for consistency

### CODE REVIEW

**Comment by lwvmobile** [comment]
```
[  1%] Building C object CMakeFiles/dsd-fme.dir/src/edacs-fme.c.o
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c: In function ‘edacs’:
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c:510:38: warning: left shift count >= width of type [-Wshift-count-overflow]
  510 |     fr_1t = fr_1t ^ (state->esk_mask << 32);
      |                                      ^~
[  2%] Building C object CMakeFiles/dsd-fme.dir/git_ver.c.o

```

**Comment by lwvmobile** [comment]
That was fast.

**Comment by ilyacodes** [comment]
Whenever this gets merged in, I have a huge diff ready to go for EDACS standard - basically implementing message parsing based on the docs.

**Comment by lwvmobile** [comment]
```
[  1%] Building C object CMakeFiles/dsd-fme.dir/src/edacs-fme.c.o
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c: In function ‘get_lcn_status_string’:
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c:59:30: error: expected ‘;’ before ‘if’
   59 |     return "[Unknown Status]"
      |                              ^
      |                              ;
   60 |   if (lcn == 28)
      |   ~~                          
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c: In function ‘edacs’:
/SSD_STORAGE/2024_DEV/dsd-fme ea changes/dsd-fme/src/edacs-fme.c:693:136: error: expected ‘;’ before ‘fprintf’
  693 |         fprintf (stderr, " TDMA Group Call :: Group [%05d] Source [%08d] LCN [%02d]%s", group, source, lcn, get_lcn_status_string(lcn))
      |                                                                                                                                        ^
      |                                                                                                                                        ;
  694 |         fprintf (stderr, "%s", KNRM);
      |         ~~~~~~~                                                                                                                         
make[2]: *** [CMakeFiles/dsd-fme.dir/build.make:678: CMakeFiles/dsd-fme.dir/src/edacs-fme.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/dsd-fme.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by ilyacodes** [comment]
Ugh, I really need to get a VM up for building this...

**Comment by lwvmobile** [comment]
> Ugh, I really need to get a VM up for building this...

Its probably easier that way, and you can test changes without having me constantly building it.

**Pull request merged**
