### PR TITLE
DMR: Fix incorrect MotoTRBO Basic Privacy mask

### PR DESCRIPTION
**Pull request by ilyacodes**
Tested with an R7.

Basic Privacy key: `73_dec`
Encrypted silent voice: `860DD7D3F2AC80`
Mask: `7E0C7E4C7E4C00`

### CODE REVIEW

**Comment by lwvmobile** [comment]
Thanks, somebody else sent that in a forum reply a while back, but when I went to check, it had mysteriously vanished.

**Comment by iScottybotty** [comment]
It was I that posted, and the post immediately vanished as you describe... 

The mask is different for me:
7E 0C 7E 4C 4E 4C however I notice on Ilyacodes he includes 80 with the silent frame, 86 0D D7 D3 F2 AC (80). I don't, could explain the difference. 4E4C is perfectly clear also on test using DP4400E.

I'll try 7E4C and cross check the clarity.

**Comment by ilyacodes** [comment]
> The mask is different for me: 7E 0C 7E 4C 4E 4C 

This is interesting, but likely the result of errors during the decoding process - can you try a few times and see if you get that consistently? I did get one time that (on a different key) I got some un-detected errors and got a result like the one you show.

A correct mask should be a 16-bit sub-mask repeated 3 times, followed by either `80` or `00`, and with the 3rd most-significant digit a `0` in all cases:

```
WX0Z_WXYZ_WXYZ_80  if (key & 0x02)
WX0Z_WXYZ_WXYZ_00  otherwise
```

**Comment by iScottybotty** [comment]
Ilyacodes: Yep, your absolutely correct. I've tested again using a DP3600 and the frames are a match with yours. It's pretty consistant also. I am however using a newer build on a newer machine since the discovery, perhaps the old machine could have been a bit slow... 👍

Close. 

image

**Pull request merged**
